Add link to article and license inside README
PrestaShop/theme-refacto pull request #202
Opened 2022-03-15 10:41 UTC by matks

| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Add link to article and license inside README
| Type?             | improvement
| BC breaks?        | no
| Deprecations?     | no

2022-03-15 11:14 UTC, PierreRambaud approved these changes

2022-03-16 07:57 UTC, Progi1984 requested changes
How a code extracted from the Core Repository (OSL) can have the license changed to AFL without asking all contributors ?

Ping @ttoine for the legal side.

2022-03-16 08:57 UTC, matks commented
> How a code extracted from the Core Repository (OSL) can have the license changed to AFL without asking all contributors ?
> 
> Ping @ttoine for the legal side.

@Progi1984 Classic theme was always AFL

https://github.com/PrestaShop/PrestaShop/blob/1.7.8.x/themes/classic/templates/page.tpl

2022-03-16 09:42 UTC, NeOMakinG approved these changes

2022-03-16 09:43 UTC, merged

2022-03-16 09:43 UTC, NeOMakinG commented
Thanks @matks